create extension if not exists pgcrypto;
create table if not exists public.resources(id uuid primary key default gen_random_uuid(),title text not null,description text,course_code text,course_title text,level integer check(level between 100 and 400),semester text,resource_type text not null,file_path text not null,file_name text not null,file_size bigint,downloads integer not null default 0,created_at timestamptz not null default now(),uploaded_by uuid references auth.users(id));
alter table public.resources enable row level security;
drop policy if exists "public read resources" on public.resources;
create policy "public read resources" on public.resources for select to anon,authenticated using(true);
drop policy if exists "auth insert resources" on public.resources;
create policy "auth insert resources" on public.resources for insert to authenticated with check(auth.uid()=uploaded_by);
drop policy if exists "auth update resources" on public.resources;
create policy "auth update resources" on public.resources for update to authenticated using(true) with check(true);
drop policy if exists "auth delete resources" on public.resources;
create policy "auth delete resources" on public.resources for delete to authenticated using(true);
create or replace function public.increment_download(resource_id uuid) returns void language sql security definer set search_path=public as $$ update public.resources set downloads=downloads+1 where id=resource_id; $$;
grant execute on function public.increment_download(uuid) to anon,authenticated;
insert into storage.buckets(id,name,public) values('scsn-resources','scsn-resources',true) on conflict(id) do update set public=true;
drop policy if exists "public view scsn files" on storage.objects;
create policy "public view scsn files" on storage.objects for select to anon,authenticated using(bucket_id='scsn-resources');
drop policy if exists "auth upload scsn files" on storage.objects;
create policy "auth upload scsn files" on storage.objects for insert to authenticated with check(bucket_id='scsn-resources');
drop policy if exists "auth update scsn files" on storage.objects;
create policy "auth update scsn files" on storage.objects for update to authenticated using(bucket_id='scsn-resources') with check(bucket_id='scsn-resources');
drop policy if exists "auth delete scsn files" on storage.objects;
create policy "auth delete scsn files" on storage.objects for delete to authenticated using(bucket_id='scsn-resources');
